// lib/core/services/pdf_service.dart

import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:flutter/foundation.dart';
import 'package:share_plus/share_plus.dart';
import 'package:printing/printing.dart';

class PdfService {
  /// Generate a PDF document from markdown-like content
  ///
  /// Saves to:
  /// - Android: /storage/emulated/0/Documents/KnowYourRights/
  /// - iOS: App Documents directory (accessible via Files app)
  static Future<File> generatePdf({
    required String title,
    required String content,
    String? subtitle,
    bool openAfterSave = false,
  }) async {
    try {
      print('📄 Starting PDF generation...');
      print('Title: $title');

      // Request storage permission (Android)
      if (Platform.isAndroid) {
        final permission = await _requestStoragePermission();
        if (!permission) {
          throw Exception('Storage permission denied. Please grant permission in settings.');
        }
      }

      // Create PDF document
      final pdf = pw.Document();

      // Add content to PDF
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (pw.Context context) {
            return [
              // Title
              pw.Header(
                level: 0,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      title,
                      style: pw.TextStyle(
                        fontSize: 24,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    if (subtitle != null) ...[
                      pw.SizedBox(height: 8),
                      pw.Text(
                        subtitle,
                        style: pw.TextStyle(
                          fontSize: 14,
                          color: PdfColors.grey700,
                        ),
                      ),
                    ],
                    pw.SizedBox(height: 8),
                    pw.Divider(thickness: 2),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),

              // Content
              ..._parseContent(content),

              // Footer with generation info
              pw.SizedBox(height: 40),
              pw.Divider(),
              pw.SizedBox(height: 8),
              pw.Text(
                'Generated by Know Your Rights App',
                style: pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                  fontStyle: pw.FontStyle.italic,
                ),
              ),
              pw.Text(
                'Date: ${DateTime.now().toString().split('.')[0]}',
                style: pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                ),
              ),
            ];
          },
        ),
      );

      // Save PDF to appropriate location
      final file = await _savePdf(pdf, title);

      print('✅ PDF saved successfully!');
      print('📍 Location: ${file.path}');
      print('📦 Size: ${(await file.length() / 1024).toStringAsFixed(2)} KB');

      return file;
    } catch (e) {
      print('❌ Error generating PDF: $e');
      rethrow;
    }
  }

  /// Save PDF to Downloads folder (Android) or Documents (iOS)
  static Future<String?> savePdfToDownloads({
    required String title,
    required String content,
    String? subtitle,
  }) async {
    try {
      final file = await generatePdf(
        title: title,
        content: content,
        subtitle: subtitle,
      );
      return file.path;
    } catch (e) {
      print('Error saving PDF to downloads: $e');
      return null;
    }
  }

  /// Share PDF via share sheet
  static Future<void> sharePdf(File pdfFile) async {
    try {
      await Share.shareXFiles(
        [XFile(pdfFile.path)],
        subject: pdfFile.path.split('/').last,
        text: 'Legal document from Know Your Rights',
      );
    } catch (e) {
      print('Error sharing PDF: $e');
      rethrow;
    }
  }

  /// Preview PDF (shows print preview dialog)
  static Future<void> previewPdf({
    required String title,
    required String content,
    String? subtitle,
  }) async {
    try {
      // Create PDF document
      final pdf = pw.Document();

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (pw.Context context) {
            return [
              // Title
              pw.Header(
                level: 0,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      title,
                      style: pw.TextStyle(
                        fontSize: 24,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    if (subtitle != null) ...[
                      pw.SizedBox(height: 8),
                      pw.Text(
                        subtitle,
                        style: pw.TextStyle(
                          fontSize: 14,
                          color: PdfColors.grey700,
                        ),
                      ),
                    ],
                    pw.SizedBox(height: 8),
                    pw.Divider(thickness: 2),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),

              // Content
              ..._parseContent(content),

              // Footer
              pw.SizedBox(height: 40),
              pw.Divider(),
              pw.SizedBox(height: 8),
              pw.Text(
                'Generated by Know Your Rights App',
                style: pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                  fontStyle: pw.FontStyle.italic,
                ),
              ),
              pw.Text(
                'Date: ${DateTime.now().toString().split('.')[0]}',
                style: pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                ),
              ),
            ];
          },
        ),
      );

      // Show preview using printing package
      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
        name: title,
      );
    } catch (e) {
      print('Error previewing PDF: $e');
      rethrow;
    }
  }

  /// Print PDF directly
  static Future<void> printPdf({
    required String title,
    required String content,
    String? subtitle,
  }) async {
    try {
      // Create PDF document
      final pdf = pw.Document();

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (pw.Context context) {
            return [
              // Title
              pw.Header(
                level: 0,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      title,
                      style: pw.TextStyle(
                        fontSize: 24,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    if (subtitle != null) ...[
                      pw.SizedBox(height: 8),
                      pw.Text(
                        subtitle,
                        style: pw.TextStyle(
                          fontSize: 14,
                          color: PdfColors.grey700,
                        ),
                      ),
                    ],
                    pw.SizedBox(height: 8),
                    pw.Divider(thickness: 2),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),

              // Content
              ..._parseContent(content),

              // Footer
              pw.SizedBox(height: 40),
              pw.Divider(),
              pw.SizedBox(height: 8),
              pw.Text(
                'Generated by Know Your Rights App',
                style: pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                  fontStyle: pw.FontStyle.italic,
                ),
              ),
              pw.Text(
                'Date: ${DateTime.now().toString().split('.')[0]}',
                style: pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                ),
              ),
            ];
          },
        ),
      );

      // Print using printing package
      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
        name: title,
      );
    } catch (e) {
      print('Error printing PDF: $e');
      rethrow;
    }
  }

  /// Request storage permission (Android)
  static Future<bool> _requestStoragePermission() async {
    if (Platform.isAndroid) {
      // For Android 13+ (API 33+), we don't need WRITE_EXTERNAL_STORAGE
      if (await Permission.manageExternalStorage.isGranted) {
        return true;
      }

      // Request permission
      final status = await Permission.storage.request();
      if (status.isGranted) {
        return true;
      }

      // For Android 11+ (API 30+), request manage external storage
      if (await Permission.manageExternalStorage.request().isGranted) {
        return true;
      }

      return false;
    }
    return true; // iOS doesn't need permission for app documents
  }

  /// Save PDF to user-accessible location
  static Future<File> _savePdf(pw.Document pdf, String title) async {
    // Create safe filename
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final safeTitle = title
        .replaceAll(RegExp(r'[^\w\s-]'), '')
        .replaceAll(RegExp(r'\s+'), '_')
        .substring(0, title.length > 50 ? 50 : title.length);
    final fileName = '${safeTitle}_$timestamp.pdf';

    Directory directory;

    if (Platform.isAndroid) {
      // Android: Save to Documents/KnowYourRights/
      directory = Directory('/storage/emulated/0/Documents/KnowYourRights');

      // Fallback to external storage if Documents not available
      if (!await directory.exists()) {
        final externalDir = await getExternalStorageDirectory();
        if (externalDir != null) {
          directory = Directory('${externalDir.path}/Documents/KnowYourRights');
        } else {
          // Last resort: app's directory
          final appDir = await getApplicationDocumentsDirectory();
          directory = Directory('${appDir.path}/Documents');
        }
      }
    } else if (Platform.isIOS) {
      // iOS: Save to app's Documents directory (accessible via Files app)
      final appDir = await getApplicationDocumentsDirectory();
      directory = Directory('${appDir.path}/LegalDocuments');
    } else {
      // Desktop or other platforms
      final appDir = await getApplicationDocumentsDirectory();
      directory = Directory('${appDir.path}/LegalDocuments');
    }

    // Create directory if it doesn't exist
    if (!await directory.exists()) {
      await directory.create(recursive: true);
      print('📁 Created directory: ${directory.path}');
    }

    // Save PDF
    final file = File('${directory.path}/$fileName');
    await file.writeAsBytes(await pdf.save());

    return file;
  }

  /// Get the storage directory path (for display purposes)
  static Future<String> getStorageDirectoryPath() async {
    if (Platform.isAndroid) {
      return '/storage/emulated/0/Documents/KnowYourRights';
    } else if (Platform.isIOS) {
      final appDir = await getApplicationDocumentsDirectory();
      return '${appDir.path}/LegalDocuments';
    } else {
      final appDir = await getApplicationDocumentsDirectory();
      return '${appDir.path}/LegalDocuments';
    }
  }

  /// Get all saved PDFs
  static Future<List<File>> getSavedPdfs() async {
    try {
      final directoryPath = await getStorageDirectoryPath();
      final directory = Directory(directoryPath);

      if (!await directory.exists()) {
        return [];
      }

      final files = await directory
          .list()
          .where((entity) => entity is File && entity.path.endsWith('.pdf'))
          .cast<File>()
          .toList();

      // Sort by modification date (newest first)
      files.sort((a, b) {
        final aModified = a.lastModifiedSync();
        final bModified = b.lastModifiedSync();
        return bModified.compareTo(aModified);
      });

      return files;
    } catch (e) {
      print('Error getting saved PDFs: $e');
      return [];
    }
  }

  /// Delete a PDF file
  static Future<bool> deletePdf(File file) async {
    try {
      if (await file.exists()) {
        await file.delete();
        print('🗑️ Deleted PDF: ${file.path}');
        return true;
      }
      return false;
    } catch (e) {
      print('Error deleting PDF: $e');
      return false;
    }
  }

  /// Parse markdown-like content into PDF widgets
  static List<pw.Widget> _parseContent(String content) {
    final widgets = <pw.Widget>[];
    final lines = content.split('\n');

    for (var i = 0; i < lines.length; i++) {
      final line = lines[i].trim();

      if (line.isEmpty) {
        widgets.add(pw.SizedBox(height: 10));
        continue;
      }

      // Headers
      if (line.startsWith('# ')) {
        widgets.add(pw.Header(
          level: 0,
          child: pw.Text(
            line.substring(2),
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ));
        widgets.add(pw.SizedBox(height: 10));
      } else if (line.startsWith('## ')) {
        widgets.add(pw.Header(
          level: 1,
          child: pw.Text(
            line.substring(3),
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ));
        widgets.add(pw.SizedBox(height: 8));
      } else if (line.startsWith('### ')) {
        widgets.add(pw.Header(
          level: 2,
          child: pw.Text(
            line.substring(4),
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ));
        widgets.add(pw.SizedBox(height: 6));
      }
      // Bold text
      else if (line.startsWith('**') && line.endsWith('**')) {
        widgets.add(pw.Text(
          line.substring(2, line.length - 2),
          style: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            fontSize: 12,
          ),
        ));
        widgets.add(pw.SizedBox(height: 4));
      }
      // Bullet points
      else if (line.startsWith('- ') || line.startsWith('• ')) {
        widgets.add(pw.Bullet(
          text: line.substring(2),
          style: const pw.TextStyle(fontSize: 11),
        ));
        widgets.add(pw.SizedBox(height: 4));
      }
      // Horizontal rule
      else if (line.startsWith('---') || line.startsWith('___')) {
        widgets.add(pw.SizedBox(height: 10));
        widgets.add(pw.Divider());
        widgets.add(pw.SizedBox(height: 10));
      }
      // Regular text
      else {
        // Handle inline formatting
        final cleanLine = line
            .replaceAll('**', '')  // Remove bold markers
            .replaceAll('*', '')   // Remove italic markers
            .replaceAll('__', ''); // Remove underline markers

        widgets.add(pw.Text(
          cleanLine,
          style: const pw.TextStyle(fontSize: 11),
          textAlign: pw.TextAlign.justify,
        ));
        widgets.add(pw.SizedBox(height: 4));
      }
    }

    return widgets;
  }

  /// Check if storage permission is granted
  static Future<bool> hasStoragePermission() async {
    if (Platform.isAndroid) {
      return await Permission.storage.isGranted ||
          await Permission.manageExternalStorage.isGranted;
    }
    return true; // iOS doesn't need permission
  }

  /// Open app settings (for permission management)
  static Future<void> openAppSettings() async {
    await openAppSettings();
  }
}