// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtUxspFeuxr45jK2-w-6QAR--kiGrD3pM',
    appId: '1:35922963589:web:78c41f04ac07af6b770dec',
    messagingSenderId: '35922963589',
    projectId: 'know-your-rights-2c062',
    authDomain: 'know-your-rights-2c062.firebaseapp.com',
    storageBucket: 'know-your-rights-2c062.firebasestorage.app',
    measurementId: 'G-JBHZ2ZW90N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYPIT26Wn-fIO32Jpjd_Qcf1bB6F2AerA',
    appId: '1:35922963589:android:dd7999e17fd09f77770dec',
    messagingSenderId: '35922963589',
    projectId: 'know-your-rights-2c062',
    storageBucket: 'know-your-rights-2c062.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2TZXpwHCfq7EsePQkqE2-qUMA8HdWv8',
    appId: '1:35922963589:ios:95e61ba02076bb54770dec',
    messagingSenderId: '35922963589',
    projectId: 'know-your-rights-2c062',
    storageBucket: 'know-your-rights-2c062.firebasestorage.app',
    iosBundleId: 'com.example.legalAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2TZXpwHCfq7EsePQkqE2-qUMA8HdWv8',
    appId: '1:35922963589:ios:95e61ba02076bb54770dec',
    messagingSenderId: '35922963589',
    projectId: 'know-your-rights-2c062',
    storageBucket: 'know-your-rights-2c062.firebasestorage.app',
    iosBundleId: 'com.example.legalAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtUxspFeuxr45jK2-w-6QAR--kiGrD3pM',
    appId: '1:35922963589:web:8f78f6dcb1e97a47770dec',
    messagingSenderId: '35922963589',
    projectId: 'know-your-rights-2c062',
    authDomain: 'know-your-rights-2c062.firebaseapp.com',
    storageBucket: 'know-your-rights-2c062.firebasestorage.app',
    measurementId: 'G-W2V6J1Z73E',
  );
}
